[manifest]
version = "1.0.0"
priority = 0


# Disallow usage Tarot cards that give enhancements when a Brick is chosen
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = """
if self.ability.consumeable.mod_num >= #G.hand.highlighted and #G.hand.highlighted >= (self.ability.consumeable.min_highlighted or 1) then
    return true
end
"""
position = "before"
payload = """
if self.ability.name == "The Magician"
or self.ability.name == "The Empress"
or self.ability.name == "The Hierophant"
or self.ability.name == "The Chariot"
or self.ability.name == "Justice"
or self.ability.name == "The Devil"
or self.ability.name == "The Tower"
then
    for _, card in ipairs(G.hand.highlighted) do
        if SMODS.has_enhancement(card, "m_ssnd_brick") then
            return false
        end
    end
end
"""
match_indent = true