[manifest]
version = "1.0.0"
priority = 0


# Perishable Jokers now cost half as much
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = """
self.cost = math.max(1, math.floor((self.base_cost + self.extra_cost + 0.5)*(100-G.GAME.discount_percent)/100))
"""
position = "at"
payload = """
self.cost = math.max(1, math.floor((self.base_cost + self.extra_cost + 0.5)*(100-G.GAME.discount_percent)/(self.ability.perishable and 2 or 1)/100))
"""
match_indent = true


