[manifest]
version = "1.0.0"
priority = 0


# Disable LOVE console (DebugPlus's in-game console is good enough)
[[patches]]
[patches.pattern]
target = "conf.lua"
pattern = """
t.console = not _RELEASE_MODE
"""
position = "at"
payload = """
t.console = false
"""
match_indent = true