[manifest]
version = "1.0.0"
priority = 0


# Allow Eternal to be applied to playing cards
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = """
function Card:set_eternal(_eternal)
    self.ability.eternal = nil
    if self.config.center.eternal_compat and not self.ability.perishable then
        self.ability.eternal = _eternal
    end
end
"""
position = "at"
payload = """
function Card:set_eternal(_eternal)
    self.ability.eternal = nil
    local center = self.config.center
    if (center.set == "Base" or center.set == "Enhanced" or center.eternal_compat) and not self.ability.perishable then
        self.ability.eternal = _eternal
    end
end
"""
match_indent = true


# Prevent Familiar, Grim, and Incantation from choosing Eternal playing cards when randomly choosing cards to destroy
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = """
destroyed_cards[#destroyed_cards+1] = pseudorandom_element(G.hand.cards, pseudoseed('random_destroy'))
"""
position = "at"
payload = """
local candidates = {}

for _, card in ipairs(G.hand.cards) do
    if not card.ability.eternal then
        candidates[#candidates + 1] = card
    end
end

if #candidates > 0 then
    destroyed_cards[#destroyed_cards + 1] = pseudorandom_element(candidates, pseudoseed('random_destroy'))
end

"""
match_indent = true


# Prevent Immolate from choosing Eternal playing cards when randomly choosing cards to destroy
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = """
local temp_hand = {}
for k, v in ipairs(G.hand.cards) do temp_hand[#temp_hand+1] = v end
"""
position = "at"
payload = """
local temp_hand = {}
for _, card in ipairs(G.hand.cards) do
    if not card.ability.eternal then
        temp_hand[#temp_hand + 1] = card
    end
end
"""
match_indent = true


# Prevent Trading Card from destroying Eternal playing cards
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = """
if self.ability.name == 'Trading Card' and not context.blueprint and 
G.GAME.current_round.discards_used <= 0 and #context.full_hand == 1 then
"""
position = "at"
payload = """
-- (Seasoned) Added Trading Card compatibility with Eternal playing cards
if self.ability.name == 'Trading Card' and not context.blueprint and 
G.GAME.current_round.discards_used <= 0 and #context.full_hand == 1
and not SMODS.is_eternal(context.full_hand[1], nil) then
"""
match_indent = true


# Disallow The Hanged Man, Death, and Cryptid from being used when an Eternal playing card is chosen
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = """
if self.ability.consumeable.mod_num >= #G.hand.highlighted and #G.hand.highlighted >= (self.ability.consumeable.min_highlighted or 1) then
    return true
end
"""
position = "before"
payload = """
if self.ability.name == "The Hanged Man" or self.ability.name == "Death" or self.ability.name == "Cryptid" then
    for _, card in ipairs(G.hand.highlighted) do
        if card.ability.eternal then
            return false
        end
    end
end

"""
match_indent = true