[manifest]
version = "1.0.0"
priority = 0


# Rental Jokers can now only appear starting Ante 2
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = """
if G.GAME.modifiers.enable_rentals_in_shop and pseudorandom((area == G.pack_cards and 'packssjr' or 'ssjr')..G.GAME.round_resets.ante) > 0.7 and not SMODS.Stickers["rental"].should_apply then
"""
position = "at"
payload = """
if G.GAME.modifiers.enable_rentals_in_shop and G.GAME.round_resets.ante >= 2 and pseudorandom((area == G.pack_cards and 'packssjr' or 'ssjr')..G.GAME.round_resets.ante) > 0.7 and not SMODS.Stickers["rental"].should_apply then
"""
match_indent = true